### PR TITLE
Allow for setting the annotation for strings

### PR DESCRIPTION
**Pull request by kentcdodds**
What do you all think?

### CODE REVIEW

**Comment by thymikee** [comment]
PR as feature request 👍. Yea, I initially wanted this to work that way, I think I just forgot. This needs some documentation (and type annotations), would you mind to provide that? :)

**Comment by kentcdodds** [comment]
I'm not sure how to add type annotations for these changes I'm afraid, but I can document it :)

**Comment by kentcdodds** [comment]
Docs added. Sorry, not sure on the type annotations.

**Comment by thymikee** [comment]
I'll add them in a minute, thanks!

**Comment by thymikee** [comment]
v0.2.1 released, enjoy! And make sure you're using new snapshot serializer ;)

**Comment by kentcdodds** [comment]
Great! Thanks!

**Pull request merged**
